### PR TITLE
added reduce and eq instance

### PR DESCRIPTION
**Pull request by Thimoteus**

### CODE REVIEW

**Comment by anttih** [comment]
Sorry I didn't notice your PR in time and made some changes. Can you rebase this?

Also, I think `reduce` should be private and we could reduce the value in `%`. What do you think?

**Comment by Thimoteus** [comment]
Sounds good, just made those changes. How is it now?

**Comment by anttih** [comment]
I have some quickcheck tests here locally using your Eq instance. The tests fail after you added the `reduce` calls to the instances, not exactly sure why. Anyways, let's remove the `reduce` calls from the instances and from `(%)` since that calculation is redundant. I think it's enough if we only reduce in Eq.

**Comment by anttih** [comment]
Oh, and can you squash the commits?

**Comment by anttih** [comment]
@Thimoteus I cherry-picked your stuff, so closing this. Thank you for working on this. :+1:

**Pull request closed without merging**
