### PR TITLE
use BigInt instead of Int

### PR DESCRIPTION
**Pull request by gbagan**
This ia PR following the advice of @hdgarrood   https://github.com/purescript-contrib/purescript-rationals/issues/33

The changes are:

- Rational is now a newtype over `Ratio BigInt`.
- Add a dependency on `bigints` and remove the dependency on `integers`
- numerator and denominator now return BigInts
- % is polymorphic. It accepts Int -> Int -> Rational or BigInt -> BigInt > Rational. This minimizes breaks.
- Update the tests

The readme needs to be updated.

### CODE REVIEW

**Review by f-f — APPROVED** [review]
I have tested this and it works, so I think it's good to merge

**Comment by f-f** [comment]
The only things to do I think should be:
- resolving conflicts
- noting somewhere (maybe add a package.json?) that this requires installing the `big-integers` JS package

**Comment by sigma-andex** [comment]
I think it would be better to make this depend on `js-bigints`, which doesn't require a npm dependency.

**Comment by gbagan** [comment]
I think the same thing now that bigints are widely adopted by browsers.
js-bigints does not require a npm dependency, is faster and easier to maintain.
Maybe we should wait for js-bigints to be transferred to purescript-contrib.

**Comment by sigma-andex** [comment]
> Maybe we should wait for js-bigints to be transferred to purescript-contrib.

Done! https://github.com/purescript-contrib/purescript-js-bigints

**Comment by f-f** [comment]
Any news on this?
@gbagan I could help with moving forward this branch if needed

**Comment by gbagan** [comment]
Hi,

Sorry for the delay.
Actually, I just need a new realease of js-bigints (which contains the last PR with toInt and toNumber).

**Comment by f-f** [comment]
New release [is out](https://github.com/purescript-contrib/purescript-js-bigints/releases/tag/v2.1.0)! (thanks @sigma-andex)

**Comment by gbagan** [comment]
Since js-bigints 2.1 is now present in the last package-set, I have replaced bigints with js-bigints as object behind Rational

**Comment by gbagan** [comment]
@f-f or someone else,
could you help me to resolve the conflicts, please?
I don't know what to do

**Comment by gbagan** [comment]
I have created a branch gbagan-master that resolve conflicts.
Do I need to make a new PR with this branch?

**Comment by f-f** [comment]
You could merge the new branch in here, but making a new PR is just easier! I can review that right away

**Comment by f-f** [comment]
Closing in favour of #42

**Pull request closed without merging**
